Api/Controllers/TestController.cs

GET /test/restaurant-owner-only
GET /test/customer-only
GET /test/customer-support-agent-only
GET /test/customer-support-manager-only
GET /test/restaurant-employee-only
GET /test/restaurant-backrooms-employee-only
GET /test/restaurant-hall-employee-only
GET /test/current-user

added TestController

---

Jenkinsfile

the Kuchnia. Also changed in docker

[FIX]MaciekM_change server's codename

---

Api/Controllers/AuthController.cs
Api/Models/Dtos/RegisterRestaurantEmployeeRequest.cs
Api/Services/UserService.cs

Refactored POST register-restaurant-employee

---

Api/Controllers/MenuController.cs
Api/Controllers/MyMenuItemController.cs
Api/Models/Dtos/Menu/CreateMenuRequest.cs
Api/Program.cs
Api/Services/RestaurantMenuService.cs

Brakuje jeszcze dodatkowej walidacji - jeżeli uwzględniać to dajcie znać gdzie

feature-MichalW-MyMenuController

---

Api/Controllers/MyRestaurantGroupsController.cs
Api/Models/Dtos/RestaurantGroup/UpdateRestaurantGroupRequest.cs
Api/Services/RestaurantGroupService.cs

Added PUT my-restaurantGroup, that changes restaurant group name

[FEATURE] MichalW PUT my-restaurantGroup

---

Api/Controllers/MenuController.cs
Api/Services/RestaurantMenuService.cs

Added POST menu-id-items that adds given list of menuIds to specific menu.

Created POST menu/int/items

---

Api/Controllers/MyRestaurantsController.cs
Api/Models/Dtos/Restaurant/UpdateRestaurantRequest.cs
Api/Services/RestaurantService.cs

Added endpoints:
- PUT my-restaurant-id

[FEATURE] PUT-my-restaurant-id

---

Api/Controllers/MyRestaurantsController.cs
Api/Data/ApiDbContext.cs
Api/Data/DbSeeder.cs
Api/Data/ISoftDeletable.cs
Api/Models/Restaurant.cs
Api/Models/RestaurantGroup.cs
Api/Services/RestaurantGroupService.cs
Api/Services/RestaurantService.cs

Dodałem końcówkę pod soft-delete dla restauracji oraz logikę do soft-deletowania grup restauracji. Zmodyfikowałem funkcje w RestaurantService i RestaurantGroupService żeby przy zwracaniu GET'ów uwzględniał że grupa lub restauracja jest już usunięta.
PS
Po testowaniu usuwania sugeruję usunąć plik z danymi i jeszcze raz je z seedować od 0.

Feature michal g delete/my restaurants/id int

---

Api/Controllers/MenuController.cs
Api/Services/RestaurantMenuService.cs

Added endpoint:
- PUT menus-id

[FEATURE] PUT menus-id

---

Api/Controllers/MenuItemController.cs
Api/Services/MenuItemsService.cs

[FEATURE] PUT /menu-items/{id:int}

---

Api/Controllers/UserController.cs
Api/Controllers/UsersController.cs
Api/Services/UserService.cs

UserController:
GET /user
PUT /user
UsersController:
GET /users/{id}
PUT /users/{id}

[FEATURE] GET i PUT dla userów

---

Api/Controllers/RestaurantTagsController.cs

[FEATURE] GET /restaurant-tags/{tag}/restaurants

---

Api/Data/DbSeeder.cs

[FEATURE] dbSeeder

---

Api/Controllers/VisitsController.cs
Api/Services/VisitService.cs
Api/Validators/CustomValidators.cs
Api/Validators/ErrorCodes.cs
Api/Validators/Visit/CreateVisitRequestValidator.cs
Api/Validators/Visit/VisitValidator.cs

Validating:
+ date >= currentDate
+ numberOfGuests >= 0
+ all Participants id's are valid and >= 0
+ restaurantId
+ tableId

POST /visits

---

Api/Controllers/RestaurantTagsController.cs
Api/Models/Dtos/Restaurant/CreateRestaurantRequest.cs
Api/Models/Dtos/Restaurant/RestaurantSummaryVM.cs
Api/Models/Dtos/Restaurant/RestaurantVM.cs
Api/Models/Dtos/Restaurant/UpdateRestaurantRequest.cs
Api/Models/Dtos/Visit/VisitSummaryVM.cs
Api/Models/Restaurant.cs
Api/Services/RestaurantGroupService.cs
Api/Services/RestaurantService.cs
Api/Services/UserService.cs
Api/Services/VisitService.cs

Jeżeli gdzieś zapomniałem czegoś uwzględnić to daj znać, bo trochę tego było

[FEATURE] Kaucja dla restauracji

---

Api/Controllers/WalletController.cs
Api/Models/Dtos/Wallet/AddMoneyRequest.cs
Api/Services/WalletService.cs
Api/Validators/Wallet/PaymentTransactionValidator.cs

- `POST /wallet/add-money`
- `GET /wallet/status`
- `GET /wallet/history`

[FEATURE] Wallet

---

Api/Controllers/RestaurantsController.cs
Api/Models/Dtos/Restaurant/NearRestaurantVM.cs
Api/Services/RestaurantService.cs
Api/Utils.cs
Api/Validators/ErrorCodes.cs

Endpoint searches for restaurants in a given radius (currently max 20km) and returns List<NearRestaurantVM> containing sorted qualified restaurants
+ distanceFrom is in meters - (15564.503 = 15,564km)
+ Added simple validation (radius cannot be less than 0 or bigger than limit)
+ Tested with https://www.calculator.net

[FEATURE] Get Restaurants

---

Api/Data/DbSeeder.cs

- johndoe restaurant 1: 3 review
- johndoe restaurant 2: 2 review
- kowalski restaurant: 18 review
- anon restaurant: 3 review
- geralt restaurant: 3 review
- paul restaurant: 0 review
- walter restaurant: 3 review

[SEED] Reviews

---

Api/Controllers/DebugController.cs
Api/Data/DbSeeder.cs
Api/Services/DebugService.cs

Added add-future-visit endpoint in Debug controller that creates example visit with orders

[FEATURE] MichalW add-future-visit

---

Api/Services/RestaurantService.cs
Api/Services/ThreadService.cs

- usunięty niepotrzebny include w GetMyRestaurantsAsync()
- zmieniona metoda GetRestaurantByIdAsync()

[FIX] Niepotrzebne ładowania kolekcji nawigacyjnych

---

Api/Controllers/DeliveriesController.cs
Api/Controllers/IngredientsController.cs
Api/Controllers/TestController.cs
Api/Identity/Roles.cs
Api/Services/MenuItemsService.cs
Api/Services/RestaurantService.cs

Ogólnie to już był zrobiony walidator do sprawdzania czy użytkownik o podanym id ma uprawnienia pracownika zaplecza (czyli backdoor || owner), więc tylko zmieniłem adnotacje i usunąłem role

Fix michal g access errors

---

Api/Controllers/MenuController.cs
Api/Services/AuthorizationService.cs
Api/Services/RestaurantGroupService.cs
Api/Services/RestaurantMenuService.cs
Api/Services/RestaurantService.cs
Api/Validators/CustomRules.cs
Api/Validators/ErrorCodes.cs
Api/Validators/Restaurant/RestaurantValidator.cs
Api/Validators/Restaurant/UpdateRestaurantRequestValidator.cs

- https://github.com/Reservant-inc/reservant-backend/issues/216
- https://github.com/Reservant-inc/reservant-backend/issues/215
- https://github.com/Reservant-inc/reservant-backend/issues/206
- https://github.com/Reservant-inc/reservant-backend/issues/201

[FIX] 500 errors

---

Api/Dtos/Users/UserEmployeeVM.cs
Api/Services/UserService.cs

Added friendStatus to returned dto

[FEATURE] Add friendStatus in GET /users/{userId}

---

Api/Controllers/UserController.cs
Api/Controllers/UsersController.cs
Api/Dtos/Reports/EscalateReportRequest.cs
Api/Dtos/Users/UserSummaryVM.cs
Api/Services/FriendService.cs
Api/Services/UserService.cs

Modified DELETE /user in a way that allows user to delete his own account.
+ if requester.id == userToDelete.id, account is getting deleted (can not longer login)
+ else, as before (method checks if user is the employee of requester)

[FEATURE] Modified DELETE /user

---

Api/Controllers/VisitsController.cs
Api/Dtos/Visits/Mappings.cs
Api/Dtos/Visits/VisitSummaryVM.cs
Api/Dtos/Visits/VisitVM.cs
Api/Models/Visit.cs
Api/Services/VisitService.cs

Added endpoint for customer to cancell a visit that didn't started yet.

[FEATURE] Cancelling a Visit

---

Api/Controllers/FriendsController.cs
Api/Controllers/ThreadController.cs
Api/Dtos/FriendRequests/FriendRequestWithPrivateThreadsVM.cs
Api/Dtos/Threads/CreatePrivateThreadRequest.cs
Api/Models/Enums/MessageThreadType.cs
Api/Models/User.cs
Api/Services/FriendService.cs
Api/Services/ThreadService.cs
Api/Validators/ErrorCodes.cs

dodane:
- nowy typ chatu
- nowy DTO dla get/friends zawierający id prywatnego chatu
- nowa końcówka do dodawania prywatnego chatu

Feat michal g add private chat
